ServerEvents.recipes(event => {
   const { avaritia } = event.recipes;
   const bweo = event.recipes.gtceu.bigger_wanzi_electrolyzer_over

   bweo('prts:bigger_wanzi_electrolyzer_over_1')
    .circuit(1)
    .itemInputs('minecraft:cobblestone','prts:basic_wanzi')
    .itemOutputs('8x gtceu:stone_dust')
    .chancedOutput('2x gtceu:stone_dust',1000,500)
    .chancedOutput('gtceu:iron_dust',1000,500)
    .chancedOutput('gtceu:copper_dust',1000,500)
    .chancedOutput('gtceu:magnesium_dust',1000,500)
    .chancedOutput('gtceu:nickel_dust',1000,500)
    .duration(40)
    .EUt(32)//圆石电解
    bweo('prts:bigger_wanzi_electrolyzer_over_2')
    .circuit(1)
    .itemInputs('minecraft:stone','prts:basic_wanzi')
    .itemOutputs('8x gtceu:stone_dust')
    .chancedOutput('2x gtceu:stone_dust',1000,500)
    .chancedOutput('gtceu:iron_dust',1000,500)
    .chancedOutput('gtceu:copper_dust',1000,500)
    .chancedOutput('gtceu:magnesium_dust',1000,500)
    .chancedOutput('gtceu:nickel_dust',1000,500)
    .duration(40)
    .EUt(32)//石头电解
    bweo('prts:bigger_wanzi_electrolyzer_over_4')
    .circuit(1)
    .itemInputs('minecraft:cobbled_deepslate','prts:basic_wanzi')
    .itemOutputs('6x gtceu:deepslate_dust')
    .chancedOutput('2x gtceu:deepslate_dust',1000,500)
    .chancedOutput('gtceu:iron_dust',2000,1000)
    .chancedOutput('gtceu:copper_dust',2500,1500)
    .chancedOutput('gtceu:magnesium_dust',1000,500)
    .chancedOutput('gtceu:nickel_dust',1000,500)
    .chancedOutput('gtceu:chromium_dust',1000,500)
    .chancedOutput('gtceu:gold_dust',1000,500)
    .duration(40)
    .EUt(32)//深板岩原岩电解
    bweo('prts:bigger_wanzi_electrolyzer_over_5')
    .circuit(1)
    .itemInputs('minecraft:deepslate','prts:basic_wanzi')
    .itemOutputs('6x gtceu:deepslate_dust')
    .chancedOutput('6x gtceu:deepslate_dust',1000,500)
    .chancedOutput('gtceu:iron_dust',2000,1000)
    .chancedOutput('gtceu:copper_dust',2500,1500)
    .chancedOutput('gtceu:magnesium_dust',1000,500)
    .chancedOutput('gtceu:nickel_dust',1000,500)
    .chancedOutput('gtceu:chromium_dust',1000,500)
    .chancedOutput('gtceu:gold_dust',1000,500)
    .duration(40)
    .EUt(32)//深板岩电解
    bweo('prts:bigger_wanzi_electrolyzer_over_3')
    .circuit(1)
    .itemInputs('gtceu:rubber_log','prts:basic_wanzi')
    .itemOutputs('2x minecraft:charcoal')
    .chancedOutput('2x gtceu:charcoal_dust',1000,500)
    .chancedOutput('gtceu:sticky_resin',100,50)
    .chancedFluidOutput(Fluid.of('gtceu:methane',600),1000,2000)
    .duration(40)
    .EUt(32)//橡胶原木电解

    bweo('prts:bigger_wanzi_electrolyzer_ores_over_1')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:lapis_dust')
    .itemOutputs('2x gtceu:lazurite_dust','2x gtceu:sodalite_dust','2x gtceu:pyrite_dust','2x gtceu:calcite_dust')
    .duration(100)
    .EUt(64)//青金石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_2')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:lazurite_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust','2x gtceu:calcium_dust','2x gtceu:sodium_dust')
    .duration(100)
    .EUt(64)//蓝金石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_3')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:sodalite_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust','2x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',2000))
    .duration(100)
    .EUt(64)//方纳石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_4')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:apatite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',2000))
    .duration(100)
    .EUt(64)//磷灰石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_5')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:scheelite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:tungsten_dust')
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//白钨矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_6')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:realgar_dust')
    .itemOutputs('2x gtceu:arsenic_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//雄黄粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_7')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pyrope_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:magnesium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//镁铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_8')
    .circuit(1)
    .itemInputs('9x prts:type_one_wanzi','gtceu:red_garnet_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:iron_dust','2x gtceu:silicon_dust','2x gtceu:magnesium_dust','2x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',6000))
    .duration(100)
    .EUt(64)//红石榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_9')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cobaltite_dust')
    .itemOutputs('2x gtceu:cobalt_dust','2x gtceu:arsenic_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//辉钴矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_10')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:basaltic_mineral_sand_dust')
    .itemOutputs('2x gtceu:magnetite_dust','2x gtceu:basalt_dust')
    .duration(100)
    .EUt(64)//玄武岩矿砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_11')
    .circuit(1)
    .itemInputs('9x prts:type_one_wanzi','gtceu:basalt_dust')
    .itemOutputs('2x gtceu:magnesium_dust','2x gtceu:iron_dust','2x gtceu:silicon_dust','2x gtceu:calcium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',6000))
    .duration(100)
    .EUt(64)//玄武岩粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_12')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:stibnite_dust')
    .itemOutputs('2x gtceu:antimony_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//辉锑矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_13')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cinnabar_dust')
    .itemOutputs('2x gtceu:sulfur_dust')
    .outputFluids(Fluid.of('gtceu:mercury',2000))
    .duration(100)
    .EUt(64)//朱砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_14')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:antimony_trioxide_dust')
    .itemOutputs('2x gtceu:antimony_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//三氧化二锑粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_15')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:uraninite_dust')
    .itemOutputs('2x gtceu:uranium_dust','2x gtceu:uranium_235_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//晶质铀矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_16')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:saltpeter_dust')
    .itemOutputs('2x gtceu:potassium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:nitrogen',2000))
    .duration(100)
    .EUt(64)//硝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_17')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:salt_dust')
    .itemOutputs('2x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',2000))
    .duration(100)
    .EUt(64)//盐粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_18')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pyrochlore_dust')
    .itemOutputs('2x gtceu:niobium_dust','2x gtceu:calcium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//烧绿石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_19')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:phosphate_dust')
    .itemOutputs('2x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//磷酸盐粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_20')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:tricalcium_phosphate_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//磷酸三钙粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_21')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:talc_dust')
    .itemOutputs('2x gtceu:magnesium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//滑石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_22')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pentlandite_dust')
    .itemOutputs('2x gtceu:nickel_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//镍黄铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_23')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:barite_dust')
    .itemOutputs('2x gtceu:barium_dust','2x gtceu:sulfur_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//重晶石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_24')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:ilmenite_dust')
    .itemOutputs('2x gtceu:iron_dust','2x gtceu:titanium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钛铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_25')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:rutile_dust')
    .itemOutputs('2x gtceu:titanium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//金红石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_26')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cassiterite_dust')
    .itemOutputs('2x gtceu:tin_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//锡石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_27')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:tungstate_dust')
    .itemOutputs('2x gtceu:tungsten_dust','2x gtceu:lithium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钨酸锂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_28')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:bauxite_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:rutile_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//铝土矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_29')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:alunite_dust')
    .itemOutputs('2x gtceu:potassium_dust','2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//明矾石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_30')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:almandine_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust','2x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//铁铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_31')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:spessartine_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust','2x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//锰铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_32')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:sphalerite_dust')
    .itemOutputs('2x gtceu:zinc_dust','2x gtceu:sulfur_dust','2x gtceu:gallium_dust')
    .duration(100)
    .EUt(64)//闪锌矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_33')
    .circuit(1)
    .itemInputs('9x prts:type_one_wanzi','gtceu:yellow_garnet_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:iron_dust','2x gtceu:silicon_dust','2x gtceu:aluminium_dust','2x gtceu:chromium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//黄石榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_34')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:vanadium_magnetite_dust')
    .itemOutputs('2x gtceu:iron_dust','2x gtceu:vanadium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钒磁铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_35')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:magnetite_dust')
    .itemOutputs('2x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//磁铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_36')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:trona_dust')
    .itemOutputs('2x gtceu:sodium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//天然碱粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_37')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:soda_ash_dust')
    .itemOutputs('2x gtceu:sodium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//纯碱粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_38')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:bentonite_dust')
    .itemOutputs('2x gtceu:sodium_dust','2x gtceu:magnesium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//膨润土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_39')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:tantalite_dust')
    .itemOutputs('2x gtceu:tantalum_dust','2x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钽铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_40')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cooperite_dust')
    .itemOutputs('2x gtceu:platinum_dust','2x gtceu:palladium_dust','2x gtceu:sulfur_dust','2x gtceu:nickel_dust')
    .duration(100)
    .EUt(64)//谢尔顿矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_41')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:sapphire_dust')
    .itemOutputs('2x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//蓝宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_42')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:green_sapphire_dust')
    .itemOutputs('2x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//绿色蓝宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_43')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:uvarovite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:chromium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钙铬榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_44')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:grossular_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钙铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_45')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:andradite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:iron_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钙铁榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_46')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:borax_dust')
    .itemOutputs('2x gtceu:boron_dust','2x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//硼砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_47')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:gypsum_dust')
    .itemOutputs('2x gtceu:sulfur_dust','2x gtceu:calcium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//石膏粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_48')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:bornite_dust')
    .itemOutputs('2x gtceu:copper_dust','2x gtceu:iron_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//斑铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_49')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:blue_topaz_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .outputFluids(Fluid.of('gtceu:fluorine',2000))
    .duration(100)
    .EUt(64)//蓝黄玉粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_50')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pyrite_dust')
    .itemOutputs('2x gtceu:iron_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//黄铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_51')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:magnesite_dust')
    .itemOutputs('2x gtceu:magnesium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//菱镁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_52')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:zeolite_dust')
    .itemOutputs('2x gtceu:sodium_dust','2x gtceu:calcium_dust','2x gtceu:silicon_dust','2x gtceu:aluminium_dust')
    .duration(100)
    .EUt(64)//沸石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_53')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:olivine_dust')
    .itemOutputs('2x gtceu:iron_dust','2x gtceu:magnesium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//橄榄石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_54')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:chromite_dust')
    .itemOutputs('2x gtceu:iron_dust','2x gtceu:chromium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//铬铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_55')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:soapstone_dust')
    .itemOutputs('2x gtceu:magnesium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//皂石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_56')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:calcite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//方解石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_57')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:fullers_earth_dust')
    .itemOutputs('gtceu:magnesium_dust','gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//漂白土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_58')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:goethite_dust')
    .itemOutputs('2x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//针铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_59')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:yellow_limonite_dust')
    .itemOutputs('2x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//黄褐铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_60')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:malachite_dust')
    .itemOutputs('2x gtceu:copper_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//孔雀石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_61')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pollucite_dust')
    .itemOutputs('2x gtceu:caesium_dust','2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//铯榴石电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_62')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:pyrolusite_dust')
    .itemOutputs('2x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//软锰矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_63')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:wulfenite_dust')
    .itemOutputs('2x gtceu:lead_dust','2x gtceu:molybdenum_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钼铅矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_64')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:powellite_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:molybdenum_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//钼钙矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_65')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:molybdenite_dust')
    .itemOutputs('2x gtceu:sulfur_dust','2x gtceu:molybdenum_dust')
    .duration(100)
    .EUt(64)//辉钼矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_66')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:bastnasite_dust')
    .itemOutputs('2x gtceu:cerium_dust','2x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:fluorine',2000))
    .duration(100)
    .EUt(64)//氟碳镧铈矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_67')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:lepidolite_dust')
    .itemOutputs('2x gtceu:potassium_dust','2x gtceu:lithium_dust','2x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:fluorine',2000))
    .duration(100)
    .EUt(64)//锂云母粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_68')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:diatomite_dust')
    .itemOutputs('2x gtceu:silicon_dust','2x gtceu:iron_dust','2x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//硅藻土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_69')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:hematite_dust')
    .itemOutputs('2x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//赤铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_70')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cassiterite_sand_dust')
    .itemOutputs('2x gtceu:tin_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//锡石矿砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_71')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:garnierite_dust')
    .itemOutputs('2x gtceu:nickel_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//硅镁镍矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_72')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:tetrahedrite_dust')
    .itemOutputs('2x gtceu:copper_dust','2x gtceu:sulfur_dust','2x gtceu:iron_dust','2x gtceu:antimony_dust')
    .duration(100)
    .EUt(64)//黢铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_73')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:cobalt_oxide_dust')
    .itemOutputs('2x gtceu:cobalt_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//氧化钴粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_74')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:zincite_dust')
    .itemOutputs('2x gtceu:zinc_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//红锌矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_75')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:mica_dust')
    .itemOutputs('2x gtceu:potassium_dust','2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:fluorine',2000))
    .duration(100)
    .EUt(64)//云母粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_76')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:spodumene_dust')
    .itemOutputs('2x gtceu:lithium_dust','2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//锂辉石矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_77')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:ruby_dust')
    .itemOutputs('2x gtceu:calcium_dust','2x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',2000))
    .duration(100)
    .EUt(64)//红宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_78')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:chalcopyrite_dust')
    .itemOutputs('2x gtceu:copper_dust','2x gtceu:iron_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//黄铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_79')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:glauconite_sand_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:magnesium_dust','2x gtceu:potassium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//海绿石砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_80')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:monazite_dust')
    .itemOutputs('2x gtceu:rare_earth_dust','2x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//独居石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_81')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:asbestos_dust')
    .itemOutputs('2x gtceu:silicon_dust','2x gtceu:magnesium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .duration(100)
    .EUt(64)//石棉矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_82')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:chalcocite_dust')
    .itemOutputs('2x gtceu:copper_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//辉铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_83')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:massicot_dust')
    .itemOutputs('2x gtceu:lead_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .duration(100)
    .EUt(64)//铅黄粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_84')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:galena_dust')
    .itemOutputs('2x gtceu:lead_dust','2x gtceu:sulfur_dust')
    .duration(100)
    .EUt(64)//方铅矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_ores_over_85')
    .circuit(1)
    .itemInputs('prts:type_one_wanzi','gtceu:topaz_dust')
    .itemOutputs('2x gtceu:aluminium_dust','2x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',2000))
    .outputFluids(Fluid.of('gtceu:hydrogen',2000))
    .outputFluids(Fluid.of('gtceu:fluorine',2000))
    .duration(100)
    .EUt(64)//黄玉粉电解

/////////////////多倍产率区////////////////

    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_1')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:lapis_dust')
    .itemOutputs('64x gtceu:lazurite_dust','64x gtceu:sodalite_dust','64x gtceu:pyrite_dust','64x gtceu:calcite_dust')
    .duration(800)
    .EUt(64)//青金石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_2')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:lazurite_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust','64x gtceu:calcium_dust','64x gtceu:sodium_dust')
    .duration(800)
    .EUt(64)//蓝金石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_3')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:sodalite_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust','64x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',64000))
    .duration(800)
    .EUt(64)//方纳石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_4')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:apatite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',64000))
    .duration(800)
    .EUt(64)//磷灰石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_5')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:scheelite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:tungsten_dust')
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//白钨矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_6')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:realgar_dust')
    .itemOutputs('64x gtceu:arsenic_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//雄黄粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_7')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pyrope_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//镁铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_8')
    .circuit(2)
    .itemInputs('288x prts:type_one_wanzi','32x gtceu:red_garnet_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:iron_dust','64x gtceu:silicon_dust','64x gtceu:magnesium_dust','64x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',196000))
    .duration(800)
    .EUt(64)//红石榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_9')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cobaltite_dust')
    .itemOutputs('64x gtceu:cobalt_dust','64x gtceu:arsenic_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//辉钴矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_10')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:basaltic_mineral_sand_dust')
    .itemOutputs('64x gtceu:magnetite_dust','64x gtceu:basalt_dust')
    .duration(800)
    .EUt(64)//玄武岩矿砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_11')
    .circuit(2)
    .itemInputs('288x prts:type_one_wanzi','32x gtceu:basalt_dust')
    .itemOutputs('64x gtceu:magnesium_dust','64x gtceu:iron_dust','64x gtceu:silicon_dust','64x gtceu:calcium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',196000))
    .duration(800)
    .EUt(64)//玄武岩粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_12')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:stibnite_dust')
    .itemOutputs('64x gtceu:antimony_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//辉锑矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_13')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cinnabar_dust')
    .itemOutputs('64x gtceu:sulfur_dust')
    .outputFluids(Fluid.of('gtceu:mercury',64000))
    .duration(800)
    .EUt(64)//朱砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_14')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:antimony_trioxide_dust')
    .itemOutputs('64x gtceu:antimony_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//三氧化二锑粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_15')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:uraninite_dust')
    .itemOutputs('64x gtceu:uranium_dust','64x gtceu:uranium_235_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//晶质铀矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_16')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:saltpeter_dust')
    .itemOutputs('64x gtceu:potassium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:nitrogen',64000))
    .duration(800)
    .EUt(64)//硝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_17')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:salt_dust')
    .itemOutputs('64x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',64000))
    .duration(800)
    .EUt(64)//盐粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_18')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pyrochlore_dust')
    .itemOutputs('64x gtceu:niobium_dust','64x gtceu:calcium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//烧绿石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_19')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:phosphate_dust')
    .itemOutputs('64x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//磷酸盐粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_20')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:tricalcium_phosphate_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//磷酸三钙粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_21')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:talc_dust')
    .itemOutputs('64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//滑石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_22')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pentlandite_dust')
    .itemOutputs('64x gtceu:nickel_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//镍黄铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_23')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:barite_dust')
    .itemOutputs('64x gtceu:barium_dust','64x gtceu:sulfur_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//重晶石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_24')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:ilmenite_dust')
    .itemOutputs('64x gtceu:iron_dust','64x gtceu:titanium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钛铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_25')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:rutile_dust')
    .itemOutputs('64x gtceu:titanium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//金红石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_26')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cassiterite_dust')
    .itemOutputs('64x gtceu:tin_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//锡石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_27')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:tungstate_dust')
    .itemOutputs('64x gtceu:tungsten_dust','64x gtceu:lithium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钨酸锂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_28')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:bauxite_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:rutile_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//铝土矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_29')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:alunite_dust')
    .itemOutputs('64x gtceu:potassium_dust','64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//明矾石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_30')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:almandine_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust','64x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//铁铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_31')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:spessartine_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust','64x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//锰铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_32')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:sphalerite_dust')
    .itemOutputs('64x gtceu:zinc_dust','64x gtceu:sulfur_dust','64x gtceu:gallium_dust')
    .duration(800)
    .EUt(64)//闪锌矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_33')
    .circuit(2)
    .itemInputs('288x prts:type_one_wanzi','32x gtceu:yellow_garnet_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:iron_dust','64x gtceu:silicon_dust','64x gtceu:aluminium_dust','64x gtceu:chromium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//黄石榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_34')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:vanadium_magnetite_dust')
    .itemOutputs('64x gtceu:iron_dust','64x gtceu:vanadium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钒磁铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_35')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:magnetite_dust')
    .itemOutputs('64x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//磁铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_36')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:trona_dust')
    .itemOutputs('64x gtceu:sodium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//天然碱粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_37')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:soda_ash_dust')
    .itemOutputs('64x gtceu:sodium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//纯碱粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_38')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:bentonite_dust')
    .itemOutputs('64x gtceu:sodium_dust','64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//膨润土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_39')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:tantalite_dust')
    .itemOutputs('64x gtceu:tantalum_dust','64x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钽铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_40')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cooperite_dust')
    .itemOutputs('64x gtceu:platinum_dust','64x gtceu:palladium_dust','64x gtceu:sulfur_dust','64x gtceu:nickel_dust')
    .duration(800)
    .EUt(64)//谢尔顿矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_41')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:sapphire_dust')
    .itemOutputs('64x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//蓝宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_42')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:green_sapphire_dust')
    .itemOutputs('64x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//绿色蓝宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_43')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:uvarovite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:chromium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钙铬榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_44')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:grossular_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钙铝榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_45')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:andradite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:iron_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钙铁榴石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_46')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:borax_dust')
    .itemOutputs('64x gtceu:boron_dust','64x gtceu:sodium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//硼砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_47')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:gypsum_dust')
    .itemOutputs('64x gtceu:sulfur_dust','64x gtceu:calcium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//石膏粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_48')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:bornite_dust')
    .itemOutputs('64x gtceu:copper_dust','64x gtceu:iron_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//斑铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_49')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:blue_topaz_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .outputFluids(Fluid.of('gtceu:fluorine',64000))
    .duration(800)
    .EUt(64)//蓝黄玉粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_50')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pyrite_dust')
    .itemOutputs('64x gtceu:iron_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//黄铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_51')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:magnesite_dust')
    .itemOutputs('64x gtceu:magnesium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//菱镁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_52')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:zeolite_dust')
    .itemOutputs('64x gtceu:sodium_dust','64x gtceu:calcium_dust','64x gtceu:silicon_dust','64x gtceu:aluminium_dust')
    .duration(800)
    .EUt(64)//沸石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_53')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:olivine_dust')
    .itemOutputs('64x gtceu:iron_dust','64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//橄榄石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_54')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:chromite_dust')
    .itemOutputs('64x gtceu:iron_dust','64x gtceu:chromium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//铬铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_55')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:soapstone_dust')
    .itemOutputs('64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//皂石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_56')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:calcite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//方解石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_57')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:fullers_earth_dust')
    .itemOutputs('64x gtceu:magnesium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//漂白土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_58')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:goethite_dust')
    .itemOutputs('64x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//针铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_59')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:yellow_limonite_dust')
    .itemOutputs('64x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//黄褐铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_60')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:malachite_dust')
    .itemOutputs('64x gtceu:copper_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//孔雀石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_61')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pollucite_dust')
    .itemOutputs('64x gtceu:caesium_dust','64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//铯榴石电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_62')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:pyrolusite_dust')
    .itemOutputs('64x gtceu:manganese_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//软锰矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_63')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:wulfenite_dust')
    .itemOutputs('64x gtceu:lead_dust','64x gtceu:molybdenum_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钼铅矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_64')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:powellite_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:molybdenum_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//钼钙矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_65')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:molybdenite_dust')
    .itemOutputs('64x gtceu:sulfur_dust','64x gtceu:molybdenum_dust')
    .duration(800)
    .EUt(64)//辉钼矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_66')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:bastnasite_dust')
    .itemOutputs('64x gtceu:cerium_dust','64x gtceu:carbon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:fluorine',64000))
    .duration(800)
    .EUt(64)//氟碳镧铈矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_67')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:lepidolite_dust')
    .itemOutputs('64x gtceu:potassium_dust','64x gtceu:lithium_dust','64x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:fluorine',64000))
    .duration(800)
    .EUt(64)//锂云母粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_68')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:diatomite_dust')
    .itemOutputs('64x gtceu:silicon_dust','64x gtceu:iron_dust','64x gtceu:aluminium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//硅藻土粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_69')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:hematite_dust')
    .itemOutputs('64x gtceu:iron_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//赤铁矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_70')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cassiterite_sand_dust')
    .itemOutputs('64x gtceu:tin_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//锡石矿砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_71')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:garnierite_dust')
    .itemOutputs('64x gtceu:nickel_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//硅镁镍矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_72')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:tetrahedrite_dust')
    .itemOutputs('64x gtceu:copper_dust','64x gtceu:sulfur_dust','64x gtceu:iron_dust','64x gtceu:antimony_dust')
    .duration(800)
    .EUt(64)//黢铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_73')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:cobalt_oxide_dust')
    .itemOutputs('64x gtceu:cobalt_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//氧化钴粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_74')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:zincite_dust')
    .itemOutputs('64x gtceu:zinc_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//红锌矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_75')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:mica_dust')
    .itemOutputs('64x gtceu:potassium_dust','64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:fluorine',64000))
    .duration(800)
    .EUt(64)//云母粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_76')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:spodumene_dust')
    .itemOutputs('64x gtceu:lithium_dust','64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//锂辉石矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_77')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:ruby_dust')
    .itemOutputs('64x gtceu:calcium_dust','64x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:chlorine',64000))
    .duration(800)
    .EUt(64)//红宝石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_78')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:chalcopyrite_dust')
    .itemOutputs('64x gtceu:copper_dust','64x gtceu:iron_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//黄铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_79')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:glauconite_sand_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:magnesium_dust','64x gtceu:potassium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//海绿石砂粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_80')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:monazite_dust')
    .itemOutputs('64x gtceu:rare_earth_dust','64x gtceu:phosphorus_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//独居石粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_81')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:asbestos_dust')
    .itemOutputs('64x gtceu:silicon_dust','64x gtceu:magnesium_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .duration(800)
    .EUt(64)//石棉矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_82')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:chalcocite_dust')
    .itemOutputs('64x gtceu:copper_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//辉铜矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_83')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:massicot_dust')
    .itemOutputs('64x gtceu:lead_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .duration(800)
    .EUt(64)//铅黄粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_84')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:galena_dust')
    .itemOutputs('64x gtceu:lead_dust','64x gtceu:sulfur_dust')
    .duration(800)
    .EUt(64)//方铅矿粉电解
    bweo('prts:bigger_wanzi_electrolyzer_big_ores_over_85')
    .circuit(2)
    .itemInputs('32x prts:type_one_wanzi','32x gtceu:topaz_dust')
    .itemOutputs('64x gtceu:aluminium_dust','64x gtceu:silicon_dust')
    .outputFluids(Fluid.of('gtceu:oxygen',64000))
    .outputFluids(Fluid.of('gtceu:hydrogen',64000))
    .outputFluids(Fluid.of('gtceu:fluorine',64000))
    .duration(800)
    .EUt(64)//黄玉粉电解

    avaritia.shaped_table(2,
        "gtceu:bigger_wanzi_electrolyzer",
        [
            "AAAAA",
            "ABCBA",
            "ABSBA",
            "ABCBA",
            "AAAAA"
        ],{
            A:'gtceu:double_stainless_steel_plate',
            B:'prts:advanced_wanzi_redirection_plate',
            C:'gtceu:mv_energy_input_hatch_16a',
            S:'gtceu:basic_model_wanzi_electrolyzer',
        })//大型万子电解机制作
})
