ServerEvents.recipes((event) => {
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_1')
    .itemInputs('prts:heteromorphic_iron')
    .itemOutputs('2x minecraft:raw_iron','2x minecraft:raw_copper')
    .chancedOutput('minecraft:raw_gold',1500,200)
    .duration(200)
    .EUt(20)//异形铁拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_2')
    .itemInputs('prts:heteromorphic_copper')
    .itemOutputs('2x gtceu:raw_hematite','2x gtceu:raw_chalcopyrite')
    .chancedOutput('gtceu:gold_dust',1500,200)
    .duration(200)
    .EUt(20)//异形铜拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_3')
    .itemInputs('prts:heteromorphic_gold')
    .itemOutputs('2x minecraft:raw_gold','2x minecraft:raw_copper')
    .chancedOutput('gtceu:raw_diamond',500,500)
    .duration(200)
    .EUt(30)//异形金拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_4')
    .itemInputs('prts:heteromorphic_diamond')
    .itemOutputs('2x gtceu:raw_diamond','2x minecraft:raw_gold')
    .chancedOutput('2x gtceu:raw_sphalerite',2500,1500)
    .duration(200)
    .EUt(30)//异形钻石拆解 

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_5')
    .itemInputs('prts:heteromorphic_tin')
    .itemOutputs('2x minecraft:raw_iron','2x gtceu:raw_tin')
    .chancedOutput('2x minecraft:raw_copper',1500,200)
    .duration(200)
    .EUt(20)//异形锡拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_6')
    .itemInputs('prts:heteromorphic_steel')
    .itemOutputs('4x gtceu:steel_ingot','2x gtceu:raw_silver')
    .chancedOutput('2x gtceu:raw_realgar',1500,500)
    .duration(200)
    .EUt(28)//异形钢拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_7')
    .itemInputs('prts:primary_void_coal')
    .itemOutputs('4x minecraft:coal','2x minecraft:raw_iron')
    .chancedOutput('2x minecraft:coal',2000,500)
    .duration(200)
    .EUt(28)//初虚化煤炭拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_8')
    .itemInputs('prts:heterolattice_lapis_lazuli')
    .itemOutputs('2x gtceu:raw_lapis','2x gtceu:raw_lead')
    .chancedOutput('2x gtceu:raw_emerald',1200,200)
    .duration(200)
    .EUt(28)//异格构青金石拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_9')
    .itemInputs('prts:crimson_stone')
    .itemOutputs('2x gtceu:raw_redstone','2x minecraft:raw_gold')
    .chancedOutput('4x gtceu:raw_rock_salt',1500,500)
    .duration(200)
    .EUt(30)//赤石拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:kuangwulixi_10')
    .itemInputs('prts:heteromorphic_jade')
    .itemOutputs('4x gtceu:raw_blue_topaz','4x gtceu:raw_topaz','4x gtceu:raw_chalcocite','4x gtceu:raw_bornite')
    .chancedOutput('4x gtceu:raw_chalcocite',1500,500)
    .chancedOutput('4x gtceu:raw_bornite',1500,500)
    .duration(200)
    .EUt(30)//异形玉拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:mokuaifenjie_1')
    .itemInputs('prts:component_module')
    .itemOutputs('prts:conventional_component')
    .chancedOutput('prts:conventional_component',5000,2500)
    .chancedOutput('prts:non_conventional_component',1000,500)
    .chancedOutput('prts:imitation_conventional_component',2500,1250)
    .duration(200)
    .EUt(30)//组件模块用途——拆解

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:general_purpose_circuit_unit_1')
    .circuit(1)
    .chancedInput('prts:disassembler_unit',1000,-200)
    .itemInputs('#gtceu:circuits/mv')
    .itemOutputs('4x prts:general_purpose_circuit_unit')
    .duration(40)
    .EUt(64)//电路通用单元制作

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:general_purpose_circuit_unit_2')
    .circuit(1)
    .chancedInput('prts:disassembler_unit',1000,-200)
    .itemInputs('#gtceu:circuits/lv')
    .itemOutputs('2x prts:general_purpose_circuit_unit')
    .duration(40)
    .EUt(64)//电路通用单元制作2

    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_1')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_electric_furnace')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV电炉获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_2')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_alloy_smelter')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV合金炉获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_3')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_arc_furnace')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV电弧炉获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_4')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_assembler')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV组装机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_5')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_autoclave')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV高压釜获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_6')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_bender')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV卷板机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_7')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_brewery')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV酿造室获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_8')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_canner')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV装罐机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_9')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_centrifuge')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV离心机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_10')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_chemical_bath')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV化学浸洗机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_11')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_chemical_reactor')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV化学反应釜获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_12')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_compressor')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV压缩机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_13')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_cutter')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV切割机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_14')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_distillery')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV蒸馏室获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_15')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_electrolyzer')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV电解机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_16')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_electromagnetic_separator')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV电磁选矿机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_17')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_extractor')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV提取机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_18')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_extruder')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV压模器获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_19')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_fermenter')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV发酵槽获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_20')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_fluid_heater')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV流体加热器获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_21')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_fluid_solidifier')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV流体固化器获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_22')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_forge_hammer')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV锻造锤获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_23')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_forming_press')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV冲压机床获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_24')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_lathe')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV车床获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_25')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_scanner')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV扫描仪获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_26')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_mixer')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV搅拌机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_27')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_ore_washer')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV洗矿厂获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_28')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_packer')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV打包机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_29')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_laser_engraver')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV激光蚀刻机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_30')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_sifter')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV筛选机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_31')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_thermal_centrifuge')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV热力离心机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_32')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_wiremill')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV线材轧机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_33')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_macerator')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV研磨机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_34')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_gas_collector')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV集气室获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_35')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_rock_crusher')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV碎岩机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_36')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_pump')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV泵获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_37')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_fisher')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV钓鱼机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_38')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_block_breaker')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV方块破坏器获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_39')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_miner')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV采矿机获取蓝图
    event.recipes.gtceu.basic_model_wanzi_disassembler('prts:super_diaassembler_40')
    .circuit(9)
    .chancedInput('prts:disassembler_unit',400,-200)
    .itemInputs('gtceu:lv_item_collector')
    .chancedOutput('prts:blueprint_single_wire',500,2500)
    .chancedOutput('prts:blueprint_fine_wire',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_rotor',500,2500)
    .chancedOutput('prts:blueprint_rod',500,2500)
    .chancedOutput('prts:blueprint_gear',500,2500)
    .chancedOutput('prts:blueprint_small_gear',500,2500)
    .chancedOutput('prts:blueprint_plate',500,2500)
    .chancedOutput('prts:blueprint_ring',500,2500)
    .duration(200)
    .EUt(32)//拆解LV物品收集器获取蓝图

    function basic_model_wanzi_disassembler(id,C,I,O,T,E){
        event.recipes.gtceu.basic_model_wanzi_disassembler(id)//别问跑不跑的动，他能跑
             .circuit(C)
             .itemInputs(I)
             .itemOutputs(O)
             .duration(T)
             .EUt(E)
    }//拆解机配方代码
    basic_model_wanzi_disassembler('ka_cha_1',1,[
        'prts:zhimitiekuai'
    ],[
        '2x prts:basic_wanzi',
        'prts:refined_etched_iron_block',
        '3x minecraft:iron_block'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_2',1,[
        'prts:zhimijinkuai'
    ],[
        '4x prts:basic_wanzi',
        'prts:refined_etched_gold_block',
        'minecraft:gold_block'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_3',1,[
        'prts:zhimitongkuai'
    ],[
        '3x prts:basic_wanzi',
        'prts:refined_etched_copper_block',
        '3x minecraft:copper_block'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_4',1,[
        'prts:zhimixikuai'
    ],[
        '3x prts:basic_wanzi',
        '3x gtceu:tin_block',
        '4x gtceu:tin_dust'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_5',1,[
        'prts:zhimiqiankuai'
    ],[
        '3x gtceu:lead_block',
        '3x gtceu:lead_dust',
        '3x prts:basic_wanzi'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_6',1,[
        'prts:zhimizuanshikuai'
    ],[
        'minecraft:diamond_block',
        '2x #forge:dusts/diamond',
        '8x prts:basic_wanzi'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_7',1,[
        'prts:zhimitankuai'
    ],[
        '27x gtceu:carbon_dust',
        '2x prts:basic_wanzi'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_8',1,[
        'prts:zhimigangkuai'
    ],[
        '4x gtceu:steel_block',
        '4x gtceu:steel_dust',
        '4x prts:basic_wanzi'
    ],150,30)
    basic_model_wanzi_disassembler('ka_cha_9',1,[
        'prts:basic_wanzi_position_corrector'
    ],[
        '2x prts:basic_wanzi',
        'prts:type_d_packaging_unit',
        'prts:basic_wanzi_resistance_plate',
        'prts:basic_wanzi_redirection_plate',
        'prts:type_d_conductive_circuit',
        'prts:type_d_circuit_cross_domain_actuator'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_10',1,[
        'prts:basic_wanzi_actuator'
    ],[
        'prts:basic_wanzi',
        'gtceu:lv_electric_motor',
        'gtceu:lv_electric_piston',
        'prts:type_d_circuit_cross_domain_actuator',
        'minecraft:iron_ingot',
        'minecraft:copper_ingot'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_11',1,[
        'prts:basic_wanzi_emitter'
    ],[
        'prts:basic_wanzi',
        'gtceu:lv_electric_motor',
        'prts:basic_wanzi_holder',
        'minecraft:iron_ingot',
        'minecraft:copper_ingot'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_12',1,[
        'prts:basic_wanzi_redirection_plate'
    ],[
        '2x prts:basic_wanzi',
        'prts:type_d_circuit_cross_domain_actuator',
        'prts:type_d_conductive_circuit',
        'prts:basic_wanzi_resistance_plate'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_13',1,[
        'prts:basic_wanzi_resistance_plate'
    ],[
        '2x prts:basic_wanzi',
        'prts:micro_plastic_block',
        'minecraft:iron_ingot',
        '2x minecraft:copper_ingot'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_14',1,[
        'prts:basic_wanzi_holder'
    ],[
        'prts:type_d_packaging_unit',
        'prts:basic_wanzi_resistance_plate',
        'prts:type_d_risk_management_unit'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_15',1,[
        'prts:experimental_dsv_component'
    ],[
        'prts:type_d_conductive_circuit',
        'prts:type_d_packaging_unit',
        'prts:type_d_resistor',
        '5x prts:basic_wanzi',
        'prts:type_d_circuit_cross_domain_actuator'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_16',1,[
        'prts:type_d_risk_management_unit'
    ],[
        '2x prts:basic_wanzi',
        'minecraft:iron_ingot',
        '2x minecraft:copper_ingot',
        'prts:type_d_conductive_circuit',
        '2x prts:micro_plastic_block'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_17',1,[
        'prts:type_d_high_voltage_transformation_component'
    ],[
        'prts:type_d_conductive_circuit',
        'prts:basic_wanzi',
        'prts:type_d_resistor',
        'minecraft:iron_ingot',
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_18',1,[
        'prts:type_d_circuit_cross_domain_actuator'
    ],[
        'prts:type_one_wanjing_etched_substrate',
        'prts:basic_wanzi',
        'prts:micro_plastic_block'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_19',1,[
        'prts:micro_plastic_block'
    ],[
        'prts:basic_wanzi',
        '2x gtceu:sticky_resin'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_20',1,[
        'prts:type_d_packaging_unit'
    ],[
        'prts:basic_wanzi',
        '2x prts:micro_plastic_block',
        'minecraft:iron_ingot'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_21',1,[
        '4x prts:type_d_resistor'
    ],[
        'prts:basic_wanzi',
        'minecraft:iron_ingot',
        '2x minecraft:copper_ingot'
    ],300,30)
    basic_model_wanzi_disassembler('ka_cha_22',1,[
        'prts:type_d_conductive_circuit'
    ],[
        'prts:basic_wanzi',
        'minecraft:iron_ingot'
    ],300,30)

    event.shaped('gtceu:lv_basic_model_wanzi_disassembler',[
        "ABA",
        "CSC",
        "DDD"
    ],{
        A:'prts:basic_wanzi_impact_resistant_plate',
        B:'prts:basic_wanzi_emitter',
        C:'prts:low_voltage_wanzi_circuit',
        D:'prts:type_d_purified_high_voltage_transformation_component',
        S:'prts:experimental_dsv_component'
    })//基础万子拆解机配方
    event.shaped('gtceu:mv_basic_model_wanzi_disassembler',[
        "ABA",
        "CSC",
        "DDD"
    ],{
        A:'prts:production_type_wanzi_resistor_board',
        B:'prts:production_type_wanzi_emitter',
        C:'prts:medium_voltage_wanzi_circuit',
        D:'prts:type_c_purified_high_voltage_transformation_component',
        S:'prts:dsv_component'
    })//正式万子拆解机配方 
    event.shaped('gtceu:hv_basic_model_wanzi_disassembler',[
        "ABA",
        "CSC",
        "DDD"
    ],{
        A:'prts:advanced_wanzi_resistor_plate',
        B:'prts:advanced_wanzi_emitter',
        C:'prts:medium_voltage_wanzi_circuit',
        D:'prts:type_b_purified_high_voltage_transformation_component',
        S:'prts:production_dsv_component'
    })//进阶万子拆解机配方 
})