ServerEvents.recipes((event) => {
    function basic_model_wanzi_mining_machine(id,C,I,O,T,E,Ch1,Ch2,Ch3,Ch4,CHT1,CHT2,CHT3,CHT4,CHT5,CHT6,CHT7,CHT8,NO1,NO2){
        event.recipes.gtceu.basic_model_wanzi_mining_machine(id)
             .circuit(C)
             .itemInputs(I)
             .itemOutputs(O)
             .duration(T)
             .EUt(E)
             .chancedOutput(Ch1,CHT1,CHT2)
             .chancedOutput(Ch2,CHT3,CHT4)
             .chancedOutput(Ch3,CHT5,CHT6)
             .chancedOutput(Ch4,CHT7,CHT8)
             .notConsumable(NO1)
             .notConsumable(NO2)
    }//基础型万子采矿机代码，以下为万子采矿配方实现代码
    basic_model_wanzi_mining_machine('wanzi_mining',0,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_basaltic_mineral_sand',
        'gtceu:raw_granitic_mineral_sand',
        'gtceu:raw_fullers_earth',
        'gtceu:raw_gypsum'
    ],20,15,
    'gtceu:raw_basaltic_mineral_sand',
    'gtceu:raw_granitic_mineral_sand',
    'gtceu:raw_fullers_earth',
    'gtceu:raw_gypsum',2000,5000,2000,5000,1500,7500,1500,7500,
    'prts:crude_etched_iron_block',
    'prts:crude_etched_iron_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_1',1,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_yellow_limonite',
        'gtceu:raw_malachite',
        'gtceu:raw_goethite',
        'gtceu:raw_hematite'
    ],20,15,
    'gtceu:raw_yellow_limonite',
    'gtceu:raw_malachite',
    'gtceu:raw_goethite',
    'gtceu:raw_hematite',
    2000,5000,1500,7500,2000,5000,2000,5000,
    'prts:crude_etched_iron_block',
    'prts:crude_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_2',2,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_chalcopyrite',
        'minecraft:raw_iron',
        'gtceu:raw_pyrite',
        'minecraft:raw_copper'
    ],20,15,
    'gtceu:raw_chalcopyrite',
    'minecraft:raw_iron',
    'gtceu:raw_pyrite',
    'minecraft:raw_copper',
    2000,5000,2000,5000,2000,5000,2000,5000,
    'prts:crude_etched_iron_block',
    'prts:crude_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_3',1,[
        '2x prts:basic_wanzi'
    ],[
        'minecraft:raw_gold',
        'gtceu:raw_magnetite',
        'gtceu:raw_vanadium_magnetite'
    ],20,20,
    'minecraft:raw_gold',
    'gtceu:raw_magnetite',
    'gtceu:raw_vanadium_magnetite',
    'gtceu:waw_dust',
    1500,5000,2000,5000,2000,5000,500,500,
    'prts:crude_etched_iron_block',
    'prts:crude_etched_gold_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_4',3,[
        '2x prts:basic_wanzi',
        '#forge:ingots/tin'
    ],[
        'gtceu:raw_chalcopyrite',
        'gtceu:raw_zeolite',
        'gtceu:raw_cassiterite',
        'gtceu:raw_cassiterite_sand'
    ],20,20,
        'gtceu:raw_chalcopyrite',
        'gtceu:raw_zeolite',
        'gtceu:raw_cassiterite',
        'gtceu:raw_cassiterite_sand',
    2500,5000,5000,5000,5000,5000,5000,5000,
    'prts:crude_etched_iron_block',
    'prts:crude_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_5',0,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_basaltic_mineral_sand',
        'gtceu:raw_granitic_mineral_sand',
        'gtceu:raw_fullers_earth',
        'gtceu:raw_gypsum'
    ],20,15,
    'gtceu:raw_basaltic_mineral_sand',
    'gtceu:raw_granitic_mineral_sand',
    'gtceu:raw_fullers_earth',
    'gtceu:raw_gypsum',4000,7500,4000,7500,3000,2500,3000,2500,
    'prts:refined_etched_iron_block',
    'prts:refined_etched_iron_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_6',1,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_yellow_limonite',
        'gtceu:raw_malachite',
        'gtceu:raw_goethite',
        'gtceu:raw_hematite'
    ],20,15,
    'gtceu:raw_yellow_limonite',
    'gtceu:raw_malachite',
    'gtceu:raw_goethite',
    'gtceu:raw_hematite',
    4000,7500,3000,2500,4000,7500,4000,7500,
    'prts:refined_etched_iron_block',
    'prts:refined_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_7',2,[
        '2x prts:basic_wanzi'
    ],[
        'gtceu:raw_chalcopyrite',
        'minecraft:raw_iron',
        'gtceu:raw_pyrite',
        'minecraft:raw_copper'
    ],20,15,
    'gtceu:raw_chalcopyrite',
    'minecraft:raw_iron',
    'gtceu:raw_pyrite',
    'minecraft:raw_copper',
    4000,7500,4000,7500,4000,7500,4000,7500,
    'prts:refined_etched_iron_block',
    'prts:refined_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_8',1,[
        '2x prts:basic_wanzi'
    ],[
        'minecraft:raw_gold',
        'gtceu:raw_magnetite',
        'gtceu:raw_vanadium_magnetite'
    ],20,20,
    'minecraft:raw_gold',
    'gtceu:raw_magnetite',
    'gtceu:raw_vanadium_magnetite',
    'gtceu:raw_sphalerite',
    3000,7500,4000,7500,4000,7500,2000,4000,
    'prts:refined_etched_iron_block',
    'prts:refined_etched_gold_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_9',3,[
        '2x prts:basic_wanzi',
        '#forge:ingots/tin'
    ],[
        'gtceu:raw_chalcopyrite',
        'gtceu:raw_zeolite',
        'gtceu:raw_cassiterite',
        'gtceu:raw_cassiterite_sand'
    ],20,20,
        'gtceu:raw_chalcopyrite',
        'gtceu:raw_zeolite',
        'gtceu:raw_cassiterite',
        'gtceu:raw_cassiterite_sand',
    5000,7500,9000,7500,9000,7500,9000,7500,
    'prts:refined_etched_iron_block',
    'prts:refined_etched_copper_block'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_10',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:iron_yuan'
    ],[
        'prts:heteromorphic_iron',
        'prts:heteromorphic_copper'
    ],20,40,
        'prts:heteromorphic_iron',
        'prts:heteromorphic_copper',
        'prts:heteromorphic_tin',
        'prts:heteromorphic_gold',
    7500,2500,9000,7500,1500,750,500,250,
    'prts:naweigeshiketiekuai',
    'prts:naweigeshiketongkuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_11',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:aluminium'
    ],[
        'prts:heteromorphic_copper',
        'prts:heteromorphic_gold'
    ],20,40,
        'prts:heteromorphic_copper',
        'prts:heteromorphic_gold',
        'prts:heteromorphic_tin',
        'prts:heteromorphic_diamond',
    7500,7500,9000,7500,7500,7500,3000,2000,
    'prts:naweigeshiketongkuai',
    'prts:naweigeshikejinkuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_12',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:waw_yuan'
    ],[
        'prts:primary_void_coal',
        'prts:heteromorphic_diamond',
        'prts:heteromorphic_steel'
    ],20,128,
        'prts:heteromorphic_diamond',
        'prts:primary_void_coal',
        'prts:heteromorphic_steel',
        'gtceu:waw_ingot',
    7500,7500,7500,7500,7500,7500,1000,1000,
    'prts:naweigeshiketankuai',
    'prts:naweigeshikegangkuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_13',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:waw_yuan'
    ],[
        'prts:heteromorphic_diamond',
        'prts:heteromorphic_gold'
    ],20,40,
        'prts:heteromorphic_gold',
        'prts:heteromorphic_diamond',
        'prts:heteromorphic_tin',
        'prts:heteromorphic_iron',
    7500,7500,9000,5000,3000,2000,3000,2000,
    'prts:naweigeshikejinkuai',
    'prts:naweigeshiketankuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_14',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:copper_yuan'
    ],[
        'prts:crimson_stone',
        'prts:heteromorphic_gold'
    ],20,40,
        'prts:crimson_stone',
        'prts:heteromorphic_gold',
        'prts:heteromorphic_copper',
        'prts:heteromorphic_iron',
    7500,7500,9000,5000,7000,2000,3000,2000,
    'prts:naweigeshikejinkuai',
    'prts:naweigeshiketongkuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_15',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:copper_yuan'
    ],[
        'prts:heterolattice_lapis_lazuli',
        'prts:crimson_stone'
    ],20,40,
        'prts:crimson_stone',
        'prts:heterolattice_lapis_lazuli',
        'prts:heteromorphic_gold',
        'prts:heteromorphic_diamond',
    7500,7500,9000,5000,3000,2000,3000,2000,
    'prts:naweigeshikelvbaoshikuai',
    'prts:naweigeshikeqiankuai'
    )
    basic_model_wanzi_mining_machine('wanzi_mining_16',1,[
        '2x prts:type_one_wanzi',
        '2x #gtceu:waw_yuan'
    ],[
        'prts:heteromorphic_jade',
        'prts:heterolattice_lapis_lazuli',
        'prts:crimson_stone'
    ],20,64,
        'prts:heteromorphic_jade',
        'prts:heterolattice_lapis_lazuli',
        'prts:crimson_stone',
        'prts:heteromorphic_gold',
        7500,7500,7500,7500,5000,5000,4000,2000,
        'prts:naweigeshikeqiankuai',
        'prts:naweigeshikelvbaoshikuai'
    )
    event.shaped('gtceu:lv_basic_model_wanzi_mining_machine',[
        "AAA",
        "BSC",
        "DDD"
    ],{
        A:'prts:basic_wanzi_impact_resistant_plate',
        B:'prts:basic_wanzi_actuator',
        C:'prts:basic_wanzi_emitter',
        D:'prts:basic_wanzi_holder',
        S:'prts:low_voltage_wanzi_circuit'
    })//基础型万子采矿机配方 

    event.shaped('gtceu:mv_basic_model_wanzi_mining_machine',[
        "AAA",
        "BSC",
        "DDD"
    ],{
        A:'prts:production_type_wanzi_impact_resistant_plate',
        B:'prts:production_type_wanzi_actuator',
        C:'prts:production_type_wanzi_emitter',
        D:'prts:production_type_wanzi_holder',
        S:'prts:medium_voltage_wanzi_circuit'
    })//正式型万子采矿机配方 

    event.shaped('gtceu:hv_basic_model_wanzi_mining_machine',[
        "AAA",
        "BSC",
        "DDD"
    ],{
        A:'prts:advanced_wanzi_impact_plate',
        B:'prts:advanced_wanzi_actuator',
        C:'prts:advanced_wanzi_emitter',
        D:'prts:advanced_wanzi_holder',
        S:'prts:high_voltage_universal_casing'
    })//进阶型万子采矿机配方
})